### ISSUE TITLE
data-sync between local mongodb and Atlas mongodb in the cloud with offline support

### ISSUE THREAD

**Issue by mifitous** [amit221/mongodb-denormalized-data-sync#1]
Hello @amit221 
How can I configure mongodb-denormalized-data-sync to sync between local mongodb and Atlas mongodb in the cloud with offline support please?
Thanks

**Comment by amit221** [comment]
Hi @mifitous 
there is currently no way to configure  2 different clusters to sync, its a great feature but its not going to get done any time soon.
you can use the triggers and then write the update logic, the triggers get a URL, so you can put any URL u want and put your logic there,  
hope it helps
